---
- name: Install prometheus-node package
  community.general.apk:
    name:
      - prometheus-node-exporter
    state: present

- name: Configure node-exporter to disable nfsd collector
  ansible.builtin.lineinfile:
    path: /etc/conf.d/node-exporter
    regexp: '^ARGS='
    line: 'ARGS="--no-collector.nfsd"'
    create: true
    mode: '0644'

- name: Enable and start node service
  ansible.builtin.service:
    name: node-exporter
    enabled: true
    state: restarted
