- name: Make vector group
  ansible.builtin.group:
    name: vector
    state: present
    system: true

- name: Make vector user
  ansible.builtin.user:
    name: vector
    group: vector
    system: true
    shell: /sbin/nologin
    home: /var/lib/vector
    create_home: true
    state: present


- name: Make vector folder
  ansible.builtin.file:
    path: /var/lib/vector
    state: directory
    owner: vector
    group: vector
    mode: "755"

- name: Make vector folder
  ansible.builtin.file:
    path: /var/lib/vector/tmp
    state: directory
    owner: vector
    group: vector
    mode: "755"


- name: Make vector folder
  ansible.builtin.file:
    path: /etc/vector
    state: directory
    owner: vector
    group: vector
    mode: "755"

- name: Make vector folder
  ansible.builtin.file:
    path: /var/log/vector
    state: directory
    owner: vector
    group: vector
    mode: "755"

- name: Get Vector file
  ansible.builtin.get_url:
    url: https://packages.timber.io/vector/latest/vector-latest-x86_64-unknown-linux-gnu.tar.gz
    dest: /var/lib/vector/tmp/vector.tar.gz
    mode: "0755"

- name: Untar file
  ansible.builtin.unarchive:
    src: /var/lib/vector/tmp/vector.tar.gz
    dest: /var/lib/vector/tmp
    mode: "0755"
    remote_src: true

- name: Move files
  ansible.builtin.copy:
    src: "/var/lib/vector/tmp/vector-x86_64-unknown-linux-gnu/bin/vector"
    dest: /usr/local/bin/
    mode: "755"
    remote_src: true


- name: Make system file
  ansible.builtin.template:
    src: vector.j2
    dest: /etc/systemd/system/vector.service
    mode: "0644"


- name: Make ConfigFile
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: /etc/vector/vector.yaml
    mode: "0755"
    owner: vector
    group: vector

- name: Remove tempFile
  ansible.builtin.file:
    path: /var/lib/vector/tmp
    state: absent

- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start vector
  ansible.builtin.systemd:
    name: vector
    state: restarted
    enabled: true
