services:
  - domain: opnsense.bytedev.duckdns.org
    ip: 192.168.0.1
    port: 80
  - domain: technitium0.bytedev.duckdns.org
    ip: 192.168.2.2
    port: 5380
  - domain: technitium1.bytedev.duckdns.org
    ip: 192.168.2.3
    port: 5380
  - domain: truenas.bytedev.duckdns.org
    ip: 192.168.2.10
    port: 80
  - domain: portainer.bytedev.duckdns.org
    ip: 192.168.4.2
    port: 9000
  - domain: gitea.bytedev.duckdns.org
    ip: 192.168.2.80
    port: 3000
  - domain: glance.bytedev.duckdns.org
    ip: 192.168.4.3
    port: 8080
  - domain: rustfs.bytedev.duckdns.org
    ip: 192.168.2.50
    port: 9001
  - domain: s3.bytedev.duckdns.org
    ip: 192.168.2.50
    port: 9000
httpsserviec:
    - domain: proxmox.bytedev.duckdns.org
      ip: 192.168.0.2
      port: 8006