- name: Make code_server folder
  ansible.builtin.file:
    state: directory
    path: "/root/codeserver"
    mode: "755"

- name: Make code_server folder
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "755"
    owner: "10000"
    group: "10000"
  loop:
    - "/root/codeserver/config"
    - "/root/codeserver/share"
    - "/root/codeserver/workspace"
    
- name: Deploy code_server
  community.docker.docker_container:
    docker_host: unix:///var/run/docker.sock
    name: code_server
    image: zot.bytedev.duckdns.org/code_server:latest
    state: started
    pull: true
    recreate: true
    restart_policy: unless-stopped
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - /root/codeserver/config:/home/cecil/.config/code-server
      - /root/codeserver/share:/home/cecil/.local/share/code-server
      - /root/codeserver/workspace:/home/cecil/workspace
    networks:
      - name: macvlan
        ipv4_address: "{{ code_server_ip }}"
