---
# Proxmox NFS Mount Configuration

# TrueNAS Server IP
truenas_ip: "192.168.2.10"

# NFS Mount Points Configuration
nfs_mounts:
  - name: "postgresql"
    mount_origin: "/mnt/Data/postgresql"
    mount_point: "/mnt/postgresql"
    description: "PostgreSQL WAL Archive"

  - name: "git"
    mount_origin: "/mnt/Data/git"
    mount_point: "/mnt/git"
    description: "Gitea Repositories"

  - name: "gitlarge"
    mount_origin: "/mnt/Data/gitLarge"
    mount_point: "/mnt/gitlarge"
    description: "Gitea LFS Storage"

  - name: "objectstorage"
    mount_origin: "/mnt/Data/objectStorage"
    mount_point: "/mnt/objectstorage"
    description: "Object Storage"
  
  - name: "mongodb"
    mount_origin: "/mnt/Data/mongodb"
    mount_point: "/mnt/mongodb"
    description: "Mongo DB"

  - name: "observability"
    mount_origin: "/mnt/Data/observability"
    mount_point: "/mnt/observability"
    description: "Observability TechStack"

  - name: "zot"
    mount_origin: "/mnt/Data/zot"
    mount_point: "/mnt/zot"
    description: "zot"