$ANSIBLE_VAULT;1.1;AES256
62306461393364313530356235613863396561316462616132343931616537333963373734306438
6337326332316636336664363936353235646139323165300a353633356239346536636666323636
66656663313761323837313466623133333635613761633931316332653431643066373963343831
3463333336663165350a316230633436316534623564616237313863663138656337333939653438
36333539616232303963313432363031353335393161323066653566326530376531623739336265
3739343438356239306531346135336163336662366532323335
