- name: Install Need Package
  community.general.apk:
    update_cache: false
    name:
      - gitea
    state: installed



- name: Make ConfigFile
  ansible.builtin.template:
    src: gitea.ini.j2
    dest: /etc/gitea.init
    mode: 644

- name: Start Gitea
  ansible.builtin.service:
    name: gitea
    state: started
    enabled: true
