all:
  children:
    proxmox:
      hosts:
        proxmox0:
          ansible_host: 192.168.0.2
    alpine:
      children:
        dns:
         hosts:
          technitium0:
            ansible_host: 192.168.2.2
          technitium1:
            ansible_host: 192.168.2.3
        HApostgresql:
          children:
            proxy0:
              hosts:
                haproxy0:
                  ansible_host: 192.168.2.30
            postgresql:
              hosts:
                db0:
                  ansible_host: 192.168.2.40
                db1:
                  ansible_host: 192.168.2.41
        HARedis:
          children:
            proxy2:
              hosts:
                haproxy2:
                  ansible_host: 192.168.2.32
            redis:
              hosts:
                db4:
                  ansible_host: 192.168.2.70
                db5:
                  ansible_host: 192.168.2.71
        Rustfs:
          hosts:
            rustfs:
              ansible_host: 192.168.2.50
        docker:
          hosts:
            docker0:
              ansible_host: 192.168.2.20
        nginx:
          hosts:
            nginx0:
              ansible_host: 192.168.5.2
        gitea:
          hosts:
            gitea0:
              ansible_host: 192.168.2.80
        observability:
          hosts:
            grafana:
              ansible_host: 192.168.2.100
            loki:
              ansible_host: 192.168.2.101
            prometheus:
              ansible_host: 192.168.2.102
    debian:
      children:
        HAmongodb:
          children:
            proxy1:
              hosts:
                haproxy1:
                  ansible_host: 192.168.2.31
            mongodb:
              hosts:
                db2: 
                  ansible_host: 192.168.2.60
                db3:  
                  ansible_host: 192.168.2.61
        redpanda:
          hosts:
            redpanda0:
              ansible_host: 192.168.2.90
              