- name: Install Package
  community.general.apk:
    name:
      - tar
    state: present

- name: Make nginx_exporter group
  ansible.builtin.group:
    name: nginx_exporter
    state: present
    system: true

- name: Make nginx_exporter user
  ansible.builtin.user:
    name: nginx_exporter
    group: nginx_exporter
    system: true
    shell: /sbin/nologin
    home: /var/lib/nginx_exporter
    create_home: true
    state: present

- name: Make nginx_exporter folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nginx_exporter
    group: nginx_exporter
    mode: "755"
  loop:
    - /var/lib/nginx_exporter
    - /var/lib/nginx_exporter/tmp
    - /etc/nginx_exporter

- name: Install nginx-prometheus-exporter
  ansible.builtin.get_url:
    url: "https://github.com/nginx/nginx-prometheus-exporter/releases/download/v{{ version }}/nginx-prometheus-exporter_{{ version }}_linux_amd64.tar.gz"
    dest: /var/lib/nginx_exporter/tmp/nginx_exporter.tar.gz
    mode: "0755"

- name: Ubtar file
  ansible.builtin.unarchive:
    src: /var/lib/nginx_exporter/tmp/nginx_exporter.tar.gz
    dest: /var/lib/nginx_exporter/tmp
    mode: "0755"
    remote_src: true

- name: Move files
  ansible.builtin.copy:
    src: "/var/lib/nginx_exporter/tmp/nginx-prometheus-exporter"
    dest: /usr/local/bin/
    mode: "755"
    remote_src: true

- name: Make system file
  ansible.builtin.template:
    src: nginx_exporter.j2
    dest: /etc/init.d/nginx_exporter
    mode: "0755"

- name: Remove temp folder
  ansible.builtin.file:
    path: /var/lib/nginx_exporter/tmp
    state: absent

- name: Remove Temp Package
  community.general.apk:
    name:
      - tar
    state: absent

- name: Enable and start nginx-exporter service
  ansible.builtin.service:
    name: nginx_exporter
    enabled: true
    state: restarted
