- name: Instsall Need Package
  ansible.builtin.apt:
    name:
      - curl

- name: Make temp folder
  ansible.builtin.file:
    path: /var/lib/tmp
    state: directory
    mode: "0755"

- name: Redpanda APT 설정 스크립트 다운로드
  ansible.builtin.get_url:
    url: https://dl.redpanda.com/nzc4ZYQK3WRGd9sy/redpanda/cfg/setup/bash.deb.sh
    dest: /var/lib/tmp/redpanda_setup.sh
    mode: '0755'

- name: Redpanda APT 설정 스크립트 실행
  ansible.builtin.command:
    cmd: /var/lib/tmp/redpanda_setup.sh
  changed_when: false

- name: Remove temp folder
  ansible.builtin.file:
    path: /var/lib/tmp
    state: absent

- name: Instasll Redpanda
  ansible.builtin.apt:
    name:
      - redpanda
    state: present

- name: Install Redpanda Connect
  ansible.builtin.command:
    cmd: rpk connect install
  changed_when: false

- name: Deploy Redpanda configuration
  ansible.builtin.template:
    src: redpanda.yaml.j2
    dest: /etc/redpanda/redpanda.yaml
    owner: redpanda
    group: redpanda
    mode: '0644'

- name: Start redpanda
  ansible.builtin.systemd:
    name: redpanda
    state: restarted
    enabled: true

- name: Remove temp Package
  ansible.builtin.apt:
    name:
      - curl
    state: absent
